apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 160027200886.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:df19894279c643c50d13c9c08d773c2f028a5564
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: computers-service
  labels:
    app: computers
spec:
  type: ClusterIP
  selector:
    app: computers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
